# Generated by Django 2.2 on 2020-11-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_userprofile_active_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_user_role', to='client.UserRoles'),
        ),
    ]
