# Generated by Django 2.2 on 2020-11-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_fitnesscenterprofile_fitnessmodalprofile_fitnessprofessionalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessCenterMemberShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCenterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='open_since',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FitnessCenterSponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fitness_center')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile')),
            ],
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='fitness_center_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterType'),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='member_ship_plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterMemberShipType'),
        ),
    ]
