# Generated by Django 2.2 on 2020-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20201119_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_stories')),
                ('description', models.TextField(default='')),
                ('instagram_link', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCenterProfileSuccessStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.SuccessStories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile')),
            ],
        ),
    ]
