# Generated by Django 2.2 on 2020-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_fitnesscenterprofilesuccessstories_successstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
