# Generated by Django 2.2 on 2020-11-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_fitnesscenterprofilesuccessstories_is_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='about_us',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='video_code',
            field=models.TextField(default=''),
        ),
    ]
