# Generated by Django 2.2 on 2020-11-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_fitnesscentergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='awards',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='hours_of_operation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='languages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='specialities',
            field=models.TextField(default=''),
        ),
    ]
