# Generated by Django 2.2 on 2020-11-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20201120_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
        migrations.CreateModel(
            name='FitnessCenterPros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fitness_center')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile')),
            ],
        ),
    ]
