# Generated by Django 2.2 on 2020-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20201122_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofessionalprofile',
            name='availability_for_in_home_training',
            field=models.IntegerField(default=0),
        ),
    ]
