# Generated by Django 2.2 on 2020-11-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20201122_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='body_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='compensation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='ethnicity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='eye_color',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='hair_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='height',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='interested_in',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='languages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='modeling_interests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='piercing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='skin_tone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='tattoos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='weight',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='working_with_media',
            field=models.IntegerField(default=0),
        ),
    ]
