# Generated by Django 2.2 on 2020-11-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20201122_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_stories')),
                ('session_name', models.TextField(default='')),
                ('activity', models.TextField(default='')),
                ('intesity_level', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('time', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('spots_available', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProfessionalAdsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remove', models.BooleanField(default=False)),
                ('ad_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.AdsInformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessProfessionalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessModalProfileAdsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remove', models.BooleanField(default=False)),
                ('ad_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.AdsInformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessModalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCenterProfileAdsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remove', models.BooleanField(default=False)),
                ('ad_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.AdsInformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile')),
            ],
        ),
    ]
