# Generated by Django 2.2 on 2020-11-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_adsinformation_fitnesscenterprofileadsinformation_fitnessmodalprofileadsinformation_fitnessprofessio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsinformation',
            old_name='intesity_level',
            new_name='intensity_level',
        ),
    ]
