# Generated by Django 2.2 on 2020-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20201122_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
