# Generated by Django 2.2 on 2020-11-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20201129_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfessionalRatingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessProfessionalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessModalRatingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessModalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCenterRatingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile')),
            ],
        ),
    ]
