# Generated by Django 2.2 on 2020-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20201206_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='profile_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='profile_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='profile_url',
            field=models.TextField(default=''),
        ),
    ]
