# Generated by Django 2.2 on 2020-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_bodytypes_clientpreferences_diettypes_ethnicitytypes_eyecolor_haircolor_skintone_tattoos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessmodalprofile',
            name='hair_length',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='fitnessmodalprofile',
            name='piercing',
            field=models.TextField(default=''),
        ),
    ]
