# Generated by Django 2.2 on 2020-12-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20201208_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='height_unit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='weight_unit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='height_unit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='weight_unit',
            field=models.TextField(default=''),
        ),
    ]
