# Generated by Django 2.2 on 2020-12-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20201209_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='fitness_pros',
            field=models.ManyToManyField(to='client.FitnessProfessionalProfile'),
        ),
    ]
