# Generated by Django 2.2 on 2020-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_fitnesscenterprofile_fitness_pros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ModellingInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
    ]
