# Generated by Django 2.2 on 2020-12-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
