# Generated by Django 2.2 on 2020-12-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
