# Generated by Django 2.2 on 2020-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_remove_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
    ]
