# Generated by Django 2.2 on 2020-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
