# Generated by Django 2.2 on 2020-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
