# Generated by Django 2.2 on 2020-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0042_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
