# Generated by Django 2.2 on 2020-12-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0043_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='gym_used2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='gym_used3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='gym_used2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='gym_used3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='gym_used2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='gym_used3',
            field=models.TextField(default=''),
        ),
    ]
