# Generated by Django 2.2 on 2020-12-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0044_auto_20201224_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
