# Generated by Django 2.2 on 2020-12-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='booking_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='booking_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='booking_link',
            field=models.TextField(default=''),
        ),
    ]
