# Generated by Django 2.2 on 2020-12-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_auto_20201224_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfessionalSponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fitness_center')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessProfessionalProfile')),
            ],
        ),
    ]
