# Generated by Django 2.2 on 2020-12-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_fitnessprofessionalsponsers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessProfessionalSponsers',
        ),
    ]
