# Generated by Django 2.2 on 2020-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_userprofile_sponser_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sponser_text',
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='sponser_text',
            field=models.TextField(default=''),
        ),
    ]
