# Generated by Django 2.2 on 2020-12-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_auto_20201224_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='address2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='address3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='gym_used',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='gym_used2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='gym_used3',
            field=models.TextField(default=''),
        ),
    ]
