# Generated by Django 2.2 on 2020-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0053_auto_20201224_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsinformation',
            name='days',
            field=models.TextField(default=''),
        ),
    ]
