# Generated by Django 3.1.3 on 2021-02-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0054_auto_20201226_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='c',
            field=models.TextField(default=''),
        ),
    ]
