# Generated by Django 3.1.3 on 2021-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0055_fitnessmodalprofile_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='video_code2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='video_code3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='video_code4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='video_code2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='video_code3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='video_code4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='video_code2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='video_code3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='video_code4',
            field=models.TextField(default=''),
        ),
    ]
