# Generated by Django 3.1.3 on 2021-02-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0056_auto_20210211_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesscenterprofile',
            name='video_code2',
        ),
        migrations.RemoveField(
            model_name='fitnesscenterprofile',
            name='video_code3',
        ),
        migrations.RemoveField(
            model_name='fitnesscenterprofile',
            name='video_code4',
        ),
        migrations.RemoveField(
            model_name='fitnessmodalprofile',
            name='video_code2',
        ),
        migrations.RemoveField(
            model_name='fitnessmodalprofile',
            name='video_code3',
        ),
        migrations.RemoveField(
            model_name='fitnessmodalprofile',
            name='video_code4',
        ),
        migrations.RemoveField(
            model_name='fitnessprofessionalprofile',
            name='video_code2',
        ),
        migrations.RemoveField(
            model_name='fitnessprofessionalprofile',
            name='video_code3',
        ),
        migrations.RemoveField(
            model_name='fitnessprofessionalprofile',
            name='video_code4',
        ),
    ]
