# Generated by Django 3.1.3 on 2021-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0059_fitnessprofessionalprofile_availability_for_on_line_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='portal_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='portal_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='portal_link',
            field=models.TextField(default=''),
        ),
    ]
