# Generated by Django 3.1.3 on 2021-02-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0060_auto_20210213_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred',
            field=models.TextField(default=''),
        ),
    ]
