# Generated by Django 3.1.3 on 2021-02-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0061_userprofile_referred'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='brands',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='brands',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='brands',
            field=models.TextField(default=''),
        ),
    ]
