# Generated by Django 3.1.3 on 2021-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0063_fitnessprofessionalprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_sponsers',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
