# Generated by Django 3.1.3 on 2021-02-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0064_professional_sponsers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional_sponsers',
            name='name',
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='sponsor_names',
            field=models.TextField(default=''),
        ),
    ]
