# Generated by Django 3.1.6 on 2021-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0065_auto_20210224_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='other_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='vimeo_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='other_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='vimeo_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='other_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='vimeo_link',
            field=models.TextField(default=''),
        ),
    ]
