# Generated by Django 3.0.4 on 2021-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0066_auto_20210302_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('hearts_counter', models.IntegerField(max_length=12)),
            ],
        ),
    ]
