# Generated by Django 3.0.4 on 2021-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_heartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartmodel',
            name='user_mail',
            field=models.EmailField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
