# Generated by Django 3.0.4 on 2021-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0068_heartmodel_user_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartmodel',
            name='user_mail',
        ),
        migrations.AddField(
            model_name='heartmodel',
            name='user_session_id',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
