# Generated by Django 3.0.4 on 2021-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0071_auto_20210303_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.IntegerField(default=0, max_length=20)),
                ('user_id', models.IntegerField(default=0, max_length=10)),
                ('hearts_counter', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='HeartModl',
        ),
    ]
