# Generated by Django 3.0.4 on 2021-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0072_auto_20210303_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartmodal',
            name='hearts_counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heartmodal',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heartmodal',
            name='user_session_id',
            field=models.IntegerField(),
        ),
    ]
