# Generated by Django 3.0.4 on 2021-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0073_auto_20210303_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartmodal',
            name='user_session_id',
            field=models.CharField(max_length=20),
        ),
    ]
