# Generated by Django 3.0.4 on 2021-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0074_auto_20210303_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('hearts_counter', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HeartModal',
        ),
    ]
