# Generated by Django 3.0.4 on 2021-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0075_auto_20210303_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heart',
            name='user_session_id',
        ),
        migrations.AddField(
            model_name='heart',
            name='user_session',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
