# Generated by Django 3.0.4 on 2021-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0078_auto_20210303_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='note_about_training_rates',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='training_methods_and_styles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
