# Generated by Django 3.0.4 on 2021-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0079_auto_20210315_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Heart_Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(default=0)),
                ('hearts_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
