# Generated by Django 2.2 on 2021-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0080_blog_heart_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenterprofile',
            name='product_reviews',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodalprofile',
            name='product_reviews',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalprofile',
            name='product_reviews',
            field=models.TextField(default=''),
        ),
    ]
