# Generated by Django 3.0.4 on 2021-04-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0081_auto_20210330_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfessionalYoutubeVideoLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessProfessionalProfile')),
            ],
        ),
    ]
