# Generated by Django 3.0.4 on 2021-04-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0083_fitnesscenteryoutubevideolinks_fitnessmodelyoutubevideolinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesscenteryoutubevideolinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessCenterProfile'),
        ),
        migrations.AlterField(
            model_name='fitnessmodelyoutubevideolinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.FitnessModalProfile'),
        ),
    ]
