# Generated by Django 3.0.4 on 2021-04-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0084_auto_20210406_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenteryoutubevideolinks',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessmodelyoutubevideolinks',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitnessprofessionalyoutubevideolinks',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
