# Generated by Django 2.2 on 2020-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('tagline', models.TextField(default='')),
                ('profile_image', models.ImageField(upload_to='brand_ambassador_image')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('featured_image', models.ImageField(upload_to='blog_featured_image')),
                ('author', models.TextField(default='')),
                ('author_profile_pic', models.ImageField(upload_to='blog_author_image')),
                ('short_description', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_page_slider_image')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
