# Generated by Django 2.2 on 2020-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_sponsorsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='second_featured_image',
            field=models.ImageField(null=True, upload_to='blog_featured_image'),
        ),
    ]
