# Generated by Django 2.2 on 2020-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20201118_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='brand_ambassador_image')),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
