# Generated by Django 2.2 on 2020-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_landingpagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedetails',
            name='banner_text',
            field=models.TextField(default=''),
        ),
    ]
