# Generated by Django 2.2 on 2020-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_auto_20201129_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedetails',
            name='facebook_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='footer_about_section',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='footer_phone_no',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='instagram_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='twitter_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='youtube_link',
            field=models.TextField(default=''),
        ),
    ]
