# Generated by Django 2.2 on 2020-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_auto_20201206_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpagedetails',
            old_name='facebook_link',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='landingpagedetails',
            old_name='instagram_link',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='landingpagedetails',
            old_name='twitter_link',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='landingpagedetails',
            old_name='youtube_link',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='youtube',
            field=models.TextField(default=''),
        ),
    ]
