# Generated by Django 2.2 on 2020-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_auto_20201206_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedetails',
            name='privacy_policy',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='terms_and_conditionss',
            field=models.TextField(default=''),
        ),
    ]
