# Generated by Django 2.2 on 2020-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_activities_certificationss_specialities'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessCenterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
    ]
