# Generated by Django 2.2 on 2020-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_fitnesscentertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_link',
            field=models.TextField(default=''),
        ),
    ]
