# Generated by Django 3.1.1 on 2021-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_ambassadorsinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSEOLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True)),
                ('site_link', models.TextField()),
            ],
        ),
    ]
