# Generated by Django 3.1.1 on 2021-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_siteseolinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteseolinks',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
